In [1]:
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
X_train , X_test, Y_train, Y_test = train_test_split(digits.data,digits.target,test_size = 0.8)

In [38]:
%matplotlib inline
import matplotlib.pyplot as plt
img = X_test[1].reshape(8,8)
plt.matshow(img)

In [12]:
Y_train[1]

6

In [44]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(64,64,64,64,64),activation = 'relu',solver = 'lbfgs',max_iter=500,alpha=1)
model.fit(X_train,Y_train)

MLPClassifier(activation='relu', alpha=1, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(64, 64, 64, 64, 64), learning_rate='constant',
              learning_rate_init=0.001, max_iter=500, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [45]:
model.score(X_test,Y_test)

0.9429763560500696

In [39]:
model.predict_proba([X_test[1]])

array([[3.17381231e-10, 4.38860472e-09, 1.13167348e-08, 9.99815234e-01,
        3.98788892e-11, 7.76177283e-07, 3.03399820e-14, 2.22138693e-08,
        2.80448553e-09, 1.83948242e-04]])

In [15]:
from sklearn.svm import SVC
model1 = SVC(kernel = 'linear')
model1.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [16]:
model1.score(X_test,Y_test)

0.958970792767733

In [29]:
from sklearn.metrics import confusion_matrix
import seaborn as sn
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
plt.figure(figsize = (20,20))
sn.heatmap(cm,annot = True)

In [30]:
cm

array([[140,   0,   0,   0,   1,   2,   1,   0,   0,   0],
       [  0, 136,   1,   0,   1,   1,   0,   0,   4,   1],
       [  0,   1, 129,   3,   0,   0,   0,   2,  10,   1],
       [  0,   0,   0, 129,   0,   4,   1,   2,   7,   1],
       [  0,   0,   0,   0, 137,   1,   0,   0,   0,   4],
       [  0,   2,   0,   0,   0, 132,   0,   1,   1,   3],
       [  0,   1,   0,   0,   1,   0, 141,   0,   0,   0],
       [  0,   0,   0,   1,   3,   0,   0, 136,   2,   1],
       [  0,   9,   2,   6,   2,   4,   1,   1, 111,   1],
       [  0,   1,   0,   7,   0,   1,   0,   5,   3, 139]], dtype=int64)

In [46]:
img

array([[ 0.,  0.,  9., 16., 16., 15.,  4.,  0.],
       [ 0.,  8., 16.,  9.,  7., 14., 11.,  0.],
       [ 0.,  5.,  5.,  1., 13., 15.,  1.,  0.],
       [ 0.,  0.,  0., 10., 16.,  7.,  0.,  0.],
       [ 0.,  0.,  0.,  1., 11., 16.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 14.,  8.,  0.],
       [ 0.,  0.,  3.,  4.,  6., 16.,  4.,  0.],
       [ 0.,  0., 14., 16., 16.,  8.,  0.,  0.]])

In [47]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
scale.fit(X_train)
X_train = scale.transform(X_train)
X_test = scale.transform(X_test)

In [51]:
model3 = MLPClassifier(hidden_layer_sizes=(64,64,64,64,64),activation='relu',solver='lbfgs',max_iter=500)
model3.fit(X_train,Y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(64, 64, 64, 64, 64), learning_rate='constant',
              learning_rate_init=0.001, max_iter=500, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [52]:
model3.score(X_test,Y_test)

0.8984700973574409